name    'nrvale0-packer'
version '0.1.4'
source 'git://github.com/nrvale0/puppet-packer'
author 'Nathan Valentine - nrvale0@gmail.com|nathan@puppetlabs.com'
license 'Apache License, Version 2.0'
summary 'Install and configure Packer'
description 'Install and configure Packer'
project_page 'http://github.com/nrvale0/puppet-packer'

dependency 'puppetlabs/stdlib', '>=3.2.0'
dependency 'nanliu/staging', '>= 0.4.0'
dependency 'AlexCline/dirtree', '>= 0.2.1'
dependency 'puppetlabs/powershell', '>= 1.0.4'
dependency 'risemoney/chocolatey', '>= 0.0.3'
